### ISSUE TITLE
Code snippet requires adjustment - Week 2, Exercise 3, Step 4.2

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#1]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week2/unit3.md#step-4define-the-composition-model

under 2.
````
composition [0..*] of ZI_RAP_Booking_#### as _Booking 
````

**Comment by CarineTD** [comment]
Hello Alex,

Can you please give more info about the issue?
I see that you’ve modified the text. , but do not understand which adjustment is required here.

The composition model is defined in Step 4 – not in the steps 1-3.

Kind regards,
  Carine

**Comment by CarineTD** [comment]
Hello Alex,

Thanks for the feedback.
*ZI_RAP_Booking_1234* will be replaced by *ZI_RAP_Booking_####*.

Kind regards,
Carine

**Comment by CarineTD** [comment]
Hello Alex,

Thanks for the feedback.
*ZI_RAP_Booking_1234* will changed to *ZI_RAP_Booking_####*.

Kind regards,
Carine
