### ISSUE TITLE
WEEK 3 UNIT 6, Step 1.5 - picture with duplicate message text

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#11]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week3/unit6.md#step-1-create-the-message-class

In step 5 the picture that shows the message text has the same text for message 001 and 002 although they are listed in a markdown table correctly just above

**Comment by CarineTD** [comment]
Hi Alex,

Thanks for the feedback.
The screenshot has been replaced.

Kind regards, 
Carine
