### ISSUE TITLE
WEEK 3 UNIT 6, Step 7.1 - screenshots of app do not show new features approve and reject

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#12]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week3/unit6.md#step-7-preview-the-enhanced-travel-app--play-around

**Comment by CarineTD** [comment]
Thanks for the feedback.
The screenshots have been replaced.

Kind regards,
Carine
