### ISSUE TITLE
Week4, Unit 3, Step 2.10 - Code snippet has different description than in screenshots and text

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#16]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week4/unit3.md#step-2-create-control-structures-and-mappings

The coded snippet in step 2.10 has the description 'Input flag structure for node Booking' while everywhere else you refer to it as 'Control structure booking'

**Comment by anfisc** [comment]
done
