### ISSUE TITLE
Week5, Unit 3, introduction - typo

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#18]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit3.md

Since we want to use the results of the remote OData service that provides a list of travel agencies in our managed travel app that we created in week 2 and 3 we will create a custom entity.

In **_contrast_** to "normal" CDS views that read data from the database from tables or other CDS views the so called custom entities act as a wrapper for a code based implementation that provides the data instead of a database table or a CDS view.

**Comment by anfisc** [comment]
done. Thanks for all the hints
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit3.md#introduction
