### ISSUE TITLE
Week5, Unit 6, Step, Change Service Binding - misleading guidance...

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#19]
in https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit6.md#check-the-service-binding
and
in https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit6.md#test-access-to-entity-agency
you ask us to select the service binding of the Greenfield implementation, but you specify the service binding from the brownfield implementation of week 4

_Note: the name of the service definition is correct_

Refering to Week2, Unit 6, we named that Service binding **```` ZUI_RAP_Travel_#### ````**
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week2/unit6.md

**```` ZUI_RAP_TRAVEL_O2_#### ````** is the name of the Brownfield implementation service binding!!!

**Comment by anfisc** [comment]
No the service binding was named

Step 2. Create the Service Binding
Now, create the service binding **ZUI_RAP_TRAVEL_O2_####** (where #### is your chosen suffix) to bind your service definition to the OData protocol.


https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week2/unit6.md#step-2-create-the-service-binding
