### ISSUE TITLE
Code snippet requires adjustment - Week 2, Exercise 3, Step 4.4

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#2]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week2/unit3.md#step-4define-the-composition-model
under 4.
````
 association to parent ZI_RAP_Travel_####        as _Travel     on  $projection.TravelUUID = _Travel.TravelUUID
````

**Comment by CarineTD** [comment]
Hello Alex,

Can you please provide more info about the reported issue?
As already mentioned in the other issue, the composition model is defined in Step 4 – not in the steps 1-3.

Kind regards,
Carine

**Comment by CarineTD** [comment]
Hello Alex,

Thanks for the feedback.
*ZI_RAP_Travel_1234* will be replaced by *ZI_RAP_Travel_####*.

Kind regards,
Carine

**Comment by CarineTD** [comment]
Hello Alex,

Thanks for the feedback.
*ZI_RAP_Travel_1234* will changed to *ZI_RAP_Travel_####*.

Kind regards,
Carine
