### ISSUE TITLE
Week 5, Unit7, Step Service binding 6)

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#21]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit7.md#create-service-binding

Service binding
a) does not show Travel with Alias as it was not provided in Code snippet.
b) does show ZCE_RAP_AGENCY_#### - the Agency extension from ES5' we just added in unit 5+6 (you might want to add a note, that beginners do not get confused)

You should add a comment that in newer version 'Activate' button was replaced by 'Publish' button and that you need to activate Service binding before pressing 'Publish'

**Comment by anfisc** [comment]
done
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit7.md#create-service-binding
