### ISSUE TITLE
Week 5, Unit 7, Intro - typo

### ISSUE THREAD

**Issue by chechsap** [SAP-samples/abap-platform-rap-opensap#26]
Subheading text ends abruptly - "This hands on script only shows the first part of the viedo for unit 7 since the second part that shows the creation of a "

**Comment by anfisc** [comment]
done
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit7.md#introduction

**Comment by anfisc** [comment]
done
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/unit7.md#introduction
