### ISSUE TITLE
Week 5, Unit 7, file W5U7_SRVD_ZAPI_RAP_TRAVEL_####.txt not provided

### ISSUE THREAD

**Issue by sandraros** [SAP-samples/abap-platform-rap-opensap#27]
The file `W5U7_SRVD_ZAPI_RAP_TRAVEL_%23%23%23%23.txt` is missing in the folder `https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/sources`:
```
@EndUserText.label: 'Travel Web API'
define service ZAPI_RAP_TRAVEL_#### {
  expose ZC_RAP_TRAVEL_#### as Travel;
}
```

**Comment by anfisc** [comment]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week5/sources/W5U7_SRVD_ZAPI_RAP_TRAVEL_%2523%2523%2523%2523.txt
