### ISSUE TITLE
typo description example Week 2 - Unit 5 - Step 2.2

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#3]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week2/unit5.md#step-2-annotate-the-booking-projection-view
see 2.

Underscore at wrong position
name and a meaningful description (e.g. ````UI Annotations for ZC_RAP_Booking_####````)

**Comment by CarineTD** [comment]
Hello Alex.

Thanks for the feedback.
We'll adjust this minor typo in the description. 

Kind regards,
  Carine
