### ISSUE TITLE
Week 3, unit 2, step 2

### ISSUE THREAD

**Issue by larshp** [SAP-samples/abap-platform-rap-opensap#6]
For **Week 3, unit 2, step 2**
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week3/unit2.md#step-2-adjust-the-behavior-definition-of-the-travel-entity

The screenshot is,
![image](https://user-images.githubusercontent.com/5888506/97859548-10dca300-1d01-11eb-81cb-d9c6368b2740.png)

and the code listed is below, instead of "1234" it should be "####"

Plus line 1 and 37 from the screenshot is missing,

looks like there is a similar issue for step 3

```code
define behavior for ZI_RAP_Travel_1234 alias Travel
persistent table zrap_atrav_1234
lock master
//authorization master ( instance )
etag master LocalLastChangedAt
{
  create;
  update;
  delete;
  association _Booking { create; }

  field ( numbering : managed, readonly ) TravelUUID;

  mapping for zrap_atrav_1234
  {
    TravelUUID         = travel_uuid;
    TravelID           = travel_id;
    AgencyID           = agency_id;
    CustomerID         = customer_id;
    BeginDate          = begin_date;
    EndDate            = end_date;
    BookingFee         = booking_fee;
    TotalPrice         = total_price;
    CurrencyCode       = currency_code;
    Description        = description;
    TravelStatus       = overall_status;
    CreatedBy          = created_by;
    CreatedAt          = created_at;
    LastChangedBy      = last_changed_by;
    LastChangedAt      = last_changed_at;
    LocalLastChangedAt = local_last_changed_at;
  }
}
```

**Comment by CarineTD** [comment]
Hallo ,

Thanks for feedback.
The suffix *_1234* has been replaced by the placeholder *_####*.

Kind regards,
  Carine

**Comment by larshp** [comment]
thanks, also I got a syntax error because I copy pasted the full code example, which is missing line 1, and maybe also line 37,

![image](https://user-images.githubusercontent.com/5888506/97863662-a0855000-1d07-11eb-9618-faf204bc7b53.png)

**Comment by CarineTD** [comment]
Hello,

In Step 2, you are not supposed to replace the whole source code, but just the behavior definition of the *Travel* entity instead.

> define behavior for ZI_RAP_Travel_#### alias Travel 
>...
>...

Kind regards,
  Carine
