### ISSUE TITLE
Missing screens in Week 3 - Unit 5

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP-samples/abap-platform-rap-opensap#7]
Screenshots for [Week 3 - Unit 5](https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week3/unit5.md) are missing (except for Step 1)
![image](https://user-images.githubusercontent.com/56556686/97868259-a54e0200-1d0f-11eb-87d4-417df6a8c58f.png)

**Comment by CarineTD** [comment]
Hello Jaime,

Thanks for the feedback.
The missing screenshot has been uploaded.

Kind regards,
  Carine
